spring.application.name=empleados
spring.config.import=optional:file:.env[.properties]

#Conexion a la abse de datos
spring.datasource.url=jdbc:mysql://localhost:3306/empleados_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

#Conexion a la abse de datos
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#Se crea la base de datos de foram automatica (none = no crear)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#Hibernate 7 ya detecta automaticamente la vesion dle mysql
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#formato sql legible y ordenado
spring.jpa.properties.hibernate.format_sql=true

#Pool de conexiones
#Espera 30 segundos por una conexion
spring.datasource.hikari.connection-timeout=30000
#Numero maximo de conexiones simultaneas
spring.datasource.hikari.maximum-pool-size=10

# Configuracion para jsp
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

#Cambiarel context path de la app
server.servlet.context-path=/empleados
#localhost:8000/empleados

#Cmbiar el puerto
server.port=8080









