spring.application.name=${APP_NAME}
spring.config.import=optional:file:.env[.properties]

#Conexion a la abse de datos
spring.datasource.url=${DB_URL}

#Conexion a la abse de datos
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#Se crea la base de datos de foram automatica (none = no crear)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#Hibernate 7 ya detecta automaticamente la vesion dle mysql
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#formato sql legible y ordenado
spring.jpa.properties.hibernate.format_sql=true

#Pool de conexiones
#Espera 30 segundos por una conexion
spring.datasource.hikari.connection-timeout=${CONNECTION_TIMEOUT}
#Numero maximo de conexiones simultaneas
spring.datasource.hikari.maximum-pool-size=${MAXIMUM_POOL_SIZE}

# Configuracion para jsp
spring.mvc.view.prefix=${JSP_PREFIX:/WEB-INF/jsp/}
spring.mvc.view.suffix=.jsp

#Cambiarel context path de la app
server.servlet.context-path=${SERVER_PATH}
#localhost:8000/empleados

#Cmbiar el puerto
server.port=${PORT:8080}


# Inicialización lazy ? no carga beans hasta que se necesitan
spring.main.lazy-initialization=true

# Quitar el warning de open-in-view
spring.jpa.open-in-view=false

# Reducir escaneo de TLDs (el log dice que tarda mucho)
server.tomcat.additional-tld-skip-patterns=*.jar

### Fix 3: Optimizar la conexión a Aiven (SSL lento)









